// DO NOT EDIT. This file is generated by CMake.
// Run CMake configure step to update it.
#include "app/game/system.h"

#define JULIUS_VERSION "1.6.0"
#define JULIUS_VERSION_SUFFIX ".74-d981e27f-dirty"

const char *system_version(void)
{
    return JULIUS_VERSION JULIUS_VERSION_SUFFIX;
}
